- hosts: host
  tasks:
   

        #- yum: 
         #    name: docker-ce
         #    state: present
      #  - yum:
       #      name: docker-ce-cli
        #     state: present

      #  - yum :
        #     name: python-pip
         #    state: present 

       # - yum:
      #       name: python-pip
     #        state: present
  

       # - pip:
        #     name: docker-py
         #    state: present
     
     #   - docker_login:
      #       username: vicky0597
       #      password: dockerhub1.@

 
        - docker_image:
             name: "cytopia/mysql-5.6"


       # - command: "mkdir /myvolume"    
   

        - docker_container:
             name: "mysql"
             image: cytopia/mysql-5.6
             restart: true
           #  networks:
           #      - name: "bridge"
             env:
                 MYSQL_ROOT_PASSWORD: "wordpress"
                 MYSQL_DATABSE: "wordpress"
                 MYSQL_USER: "wordpress"
                 MYSQL_PASSWORD: "wordpress"
             
        - command: "docker create  --name mysql -v /myvolume:/var/lib/mysql -p 3306:3306"
                 


       
     #   - command: 
        - copy:
             src: /pool
             dest: /image/php_pool 
             backup: no


        - copy:
             src: /nginx_config
             dest: /nginx_config 
             backup: no

        - unarchive:
             
             src: https://wordpress.org/latest.tar.gz
             dest: /var/www/index/
             remote_src: yes
       

        - docker_image:
             name: "server"
             tag: latest
             path: /root/docker/
             state: present


        - docker_container:
             name: wp
             image: server
            
            
             restart: true
             env:
                 WORDPRESS_DB_HOST: "wordpress:3306"
                 WORDPRESS_DB_PASSWORD: "wordpress"
                   
              
        
                           
             
